services:
  - type: web
    name: skullrecon-backend
    env: docker
    region: oregon
    plan: free
    rootDirectory: api
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "8080"
